### ISSUE TITLE
Ensure that `update_all` and `update_one` are consistent

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/arklib#41]
- [ ] Unit tests covering `update_one`
- [ ] Unit tests covering `update_all`

Then, we want to verify that:
* `update_all` can be replaced by multiple `update_one`

- [ ] Unit tests for simple cases with both `update_all` and `update_one`
- [ ] Randomized test scenario checking different combinations

**Comment by mberry** [comment]
The issue I see arising with `update_one` is that it takes a new path and old id, but also uses the path as a key with `self.path2id[path]` before updating the index. 
Think some of the functions need to be run in a different order, like the collision check at the end before returning
