### ISSUE TITLE
Test Clean-Up necessary

### ISSUE THREAD

**Issue by thinkrapido** [ARK-Builders/arklib#80]
The Test
atomic/files.rs
```
    #[test]
    fn multiple_version_files() {
```
leaves the artifact `{}_cellphoneID` in the tmp folder.

Correct Behavior: It should be cleaned up after the test.

**Comment by tareknaser** [comment]
Related conversation: https://github.com/ARK-Builders/arklib/pull/72#discussion_r1481248129
